### ISSUE TITLE
About gradient updates and 'lib'

### ISSUE THREAD

**Issue by NWPU-903PR** [dmpelt/msdnet#9]
Dear author:  
Thanks for sharing the code. This work is excellent. I would like to ask why the gradient is not subtracted in the function "updategradients_internal" of the update parameters? And how does the 'lib' function work in operations.py?

**Comment by dmpelt** [comment]
Thanks for trying out the code! Regarding your questions:

1) The gradient variable is added, not subtracted, because the training algorithm in `train.py` computes the negative of the gradient.

2) `lib` in `operations.py` refers to a C library that is compiled while installing the code using `setup.py`. The source code of this library is found in `operations.c`. When running on GPU, most of the operations are performed on GPU, which uses `gpuoperations.py` instead of `operations.py`.
